#!/bin/sh
# Publish the game data as single downloads, and write the manifest the app reads.
#
#   tools/make-data-release.sh            # laedt, hasht, laedt hoch (braucht gh)
#   NO_UPLOAD=1 tools/make-data-release.sh    # nur das Manifest ausrechnen
#
# The iOS app bundle carries no game data (an .ipa with 1.4 GB in it is nobody's
# friend, and a signed bundle cannot be written to anyway -- see patch 0017).
# It downloads the data on first start instead, and for that it needs files it
# can fetch one by one. The upstream data release is a single 1.4 GB tar.xz;
# there is no tar and no xz on iOS, so that archive is unusable there.
#
# Luckily the data release does not need unpacking at all: the game itself is
# one zip per mod, which the engine's VFS reads in place. So three things are
# republished here as plain assets:
#
#   mods/public/public.zip   the game               ~1.2 GB
#   mods/mod/mod.zip         the mod-selection UI     89 MB
#   config/*                 default.cfg and co.      a few KB
#
# and a manifest lists them with size, SHA-256 and URL. The manifest is what
# goes into the app bundle (data/download.manifest), so the hashes are pinned at
# build time: the app trusts the manifest it shipped with, not the server.
#
# The data itself is CC-BY-SA / GPL, so re-hosting is allowed; this only saves
# the phone from having to unpack an xz.
set -e

VER=${VER:-0.28.0}
TAG=${TAG:-data-$VER}
REPO=${REPO:-smatkovi/0ad-ios}
WORK=${WORK:-${TMPDIR:-/tmp}/0ad-data-release}
BASE=${BASE:-https://github.com/$REPO/releases/download/$TAG}
ARCHIVE="$WORK/0ad-$VER-unix-data.tar.xz"
URL="https://releases.wildfiregames.com/0ad-$VER-unix-data.tar.xz"

mkdir -p "$WORK/assets"

# aria2c earns its keep here: releases.wildfiregames.com gives one connection
# maybe 3 MB/s, eight of them saturate the runner. curl is the fallback.
if [ ! -e "$ARCHIVE" ]; then
    if command -v aria2c > /dev/null; then
        echo "### aria2c -x8"
        aria2c -x8 -s8 -k4M --file-allocation=none \
            -d "$WORK" -o "$(basename "$ARCHIVE")" "$URL"
    else
        echo "### curl (kein aria2c)"
        curl -fL --retry 3 -o "$ARCHIVE" "$URL"
    fi
fi
ls -l "$ARCHIVE"

echo "### auspacken"
rm -rf "$WORK/unpack"
mkdir -p "$WORK/unpack"
tar xf "$ARCHIVE" -C "$WORK/unpack" \
    "0ad-$VER/binaries/data/config" \
    "0ad-$VER/binaries/data/mods/mod" \
    "0ad-$VER/binaries/data/mods/public"
DATA="$WORK/unpack/0ad-$VER/binaries/data"

# An asset name cannot contain a slash, so the path is flattened with "--" and
# the manifest carries the real one. Nobody ever sees these names.
MANIFEST="$WORK/assets/download.manifest"
{
    echo "# 0 A.D. $VER data, for the iOS port."
    echo "# Generated by tools/make-data-release.sh -- do not edit."
    echo "# path<TAB>size<TAB>sha256<TAB>url"
} > "$MANIFEST"

rm -f "$WORK/assets"/*--* "$WORK/assets"/*.zip
cd "$DATA"
# -type f: the release has no symlinks in these paths, and a symlink would be a
# surprise worth failing on rather than following.
find config mods -type f | LC_ALL=C sort | while read -r rel; do
    asset=$(printf '%s' "$rel" | sed 's|/|--|g')
    size=$(wc -c < "$rel" | tr -d ' ')
    hash=$(sha256sum "$rel" | cut -d' ' -f1)
    ln -f "$DATA/$rel" "$WORK/assets/$asset" 2>/dev/null || cp "$DATA/$rel" "$WORK/assets/$asset"
    printf '%s\t%s\t%s\t%s/%s\n' "$rel" "$size" "$hash" "$BASE" "$asset" >> "$MANIFEST"
done

echo "### Manifest"
cat "$MANIFEST"
echo "### Summe"
awk -F'\t' '/^[^#]/ {n++; s+=$2} END {printf "%d Dateien, %.1f GB\n", n, s/1073741824}' "$MANIFEST"

if [ -n "$NO_UPLOAD" ]; then
    echo "(NO_UPLOAD -- nichts hochgeladen)"
    exit 0
fi

echo "### Freigabe $TAG"
gh release view "$TAG" -R "$REPO" > /dev/null 2>&1 || \
    gh release create "$TAG" -R "$REPO" \
        --title "0 A.D. $VER Spieldaten" \
        --notes "Die Spieldaten aus 0ad-$VER-unix-data.tar.xz, als einzelne Dateien: der iOS-Port laedt sie beim ersten Start, und auf dem Telefon gibt es kein tar und kein xz. Inhalt unveraendert, Pruefsummen in download.manifest. 0 A.D. ist GPL/CC-BY-SA, wildfiregames.com ist die Quelle."

# --clobber: running this twice must be harmless.
gh release upload "$TAG" -R "$REPO" --clobber "$WORK/assets"/*
gh release view "$TAG" -R "$REPO" --json assets -q '.assets[] | "\(.name) \(.size)"'
